#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run format
npm run lint
npm run test
npm run build

# check if dist folder exist
if [ -d ./dist ]; then
    echo ""
    echo "Build successful ✅"
fi
